### ISSUE TITLE
Integrate header into Links theme

### ISSUE THREAD

**Issue by matthewl** [matthewl/Albatross#10]
**Update the header section to use the selected options to style the header.**

The header should use the uploaded background image and the welcome message specified by the user.

### Tasks

- [ ] Use the uploaded background image for the header
- [ ] Use the persisted welcome message for the header
- [ ] Use the persisted welcome message position for the header
- [ ] Use the additional link to a page for the header
- [ ] Hide the additional link to a page behind a feature flag (`paid_feature`)
