### ISSUE TITLE
Integrate header into Desert theme

### ISSUE THREAD

**Issue by matthewl** [matthewl/Albatross#11]
Update the header section to use the selected options to style the header.

The header should use the uploaded background image and the welcome message specified by the user.

### Tasks

- [x] Use the uploaded background image for the header
- [x] Use the persisted welcome message for the header
- [x] Use the persisted welcome message position for the header
